name: helper-extras
author: Luck
version: ${project.version}
description: ${project.description}
main: me.lucko.helper.extras.ExtrasPlugin
website: https://github.com/lucko/helper
load: STARTUP
depend: [helper]
softdepend: [Citizens, ProtocolLib, ViaVersion]