name: helper-redis
author: Luck
version: ${project.version}
description: ${project.description}
main: me.lucko.helper.redis.plugin.RedisPlugin
website: https://github.com/lucko/helper
load: STARTUP
depend: [helper]