name: helper-mongo
author: Luck
version: ${project.version}
description: ${project.description}
main: me.lucko.helper.mongo.plugin.MongoPlugin
website: https://github.com/lucko/helper
load: STARTUP
depend: [helper]